import { Footer } from '@/components/layouts/footer';
import { Modal } from '@/components/layouts/modal';
import { BackToTopButton } from '@/components/ui/back-to-top-button';
import { Metadata } from 'next';
import { Charm, Jost, Oregano } from 'next/font/google';
import { Toaster } from 'sonner';

import TanstackQueryProvider from '@/components/prividers/tanstack-query-provider';
import './globals.css';

const charm = Charm({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-charm',
});

const jost = Jost({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-jost',
});

const oregano = Oregano({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-oregano',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${charm.variable} ${jost.variable} ${oregano.variable} font-jost`}
      >
        <TanstackQueryProvider>
          <div className="relative">
            <Toaster
              position="top-right"
              expand={false}
              toastOptions={{ duration: 1500 }}
            />
            <Modal />
            {children}
            <BackToTopButton />
            <Footer />
          </div>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
