import { BackToTopButton } from '@/components/ui/back-to-top-button';
import { Metadata } from 'next';
import { Charm, Jost, Oregano } from 'next/font/google';
import './globals.css';

const charm = Charm({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-charm',
});

const jost = Jost({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-jost',
});

const oregano = Oregano({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-oregano',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${charm.variable} ${jost.variable} ${oregano.variable} font-jost`}
      >
        <div className="relative">
          {children}
          <BackToTopButton />
        </div>
      </body>
    </html>
  );
}
